// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mahlbxtpgywivuwveqqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1haGxieHRwZ3l3aXZ1d3ZlcXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0OTA0MjEsImV4cCI6MjA1MzA2NjQyMX0.0zWZl5lk2aQhAn4dNVzfBgsGIPO3d4GxTVgcmhsGrFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);